service: prisma-crud

variablesResolutionMode: 20210326

package:
  patterns:
    - "!./**"
    - "ncc/**"
    # - ./config/config.json # Use for custom config JSON files

plugins:
  - serverless-offline
  - serverless-api-gateway-caching

provider:
  name: aws
  region: us-east-1
  stage: dev
  runtime: nodejs16.x
  architecture: arm64
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7
  # apiGateway: # https://www.serverless.com/framework/docs/providers/aws/events/apigateway
  #   restApiId: 'something'
  #   restApiRootResourceId: 'something'
  #   apiKeys:
  #     - key-1
  # vpc:
  #   securityGroupIds:
  #     - sg-00000000000000000
  #   subnetIds:
  #     - subnet-00000000
  environment:
    DATABASE_URL: "postgresql://postgres:password@localhost:5432/postgres?schema=public&connection_limit=1&pool_timeout=120"

functions:
  companies:
    handler: ./ncc/index.getCompanies
    memorySize: 256
    timeout: 15
    events:
      - http:
          path: api/get-companies
          method: get
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - GET
          caching:
            enabled: true
            ttlInSeconds: 300
            cacheKeyParameters:
              - name: request.querystring.skip
              - name: request.querystring.take
              - name: request.querystring.currentPage
              - name: request.querystring.sort
              - name: request.querystring.sortDirection
  create-company:
    handler: ./ncc/index.createCompany
    memorySize: 256
    events:
      - http:
          path: /api/create-company
          method: post
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - POST
  get-restaurants:
    handler: ./ncc/index.getRestaurants
    memorySize: 256
    events:
      - http:
          path: /api/get-restaurants
          method: get
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - GET
  get-restaurant:
    handler: ./ncc/index.getRestaurant
    memorySize: 256
    events:
      - http:
          path: /api/get-restaurant
          method: get
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - GET
  get-restaurant-type:
    handler: ./ncc/index.getRestaurantType
    memorySize: 256
    events:
      - http:
          path: /api/get-restaurant-type
          method: get
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - GET
  get-restaurants-by-companyId:
    handler: ./ncc/index.getRestaurantsByCompanyId
    memorySize: 256
    events:
      - http:
          path: /api/get-restaurants-by-companyId
          method: get
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - GET
  get-company-by-id:
    handler: ./ncc/index.getCompanyById
    memorySize: 256
    events:
      - http:
          path: /api/get-company-by-id
          method: get
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - GET
  create-restaurant-type:
    handler: ./ncc/index.createRestaurantType
    memorySize: 256
    events:
      - http:
          path: /api/create-restaurant-type
          method: post
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - POST
  create-restaurant:
    handler: ./ncc/index.createRestaurant
    memorySize: 256
    events:
      - http:
          path: /api/create-restaurant
          method: post
          cors:
            headers: "*"
            origin: "*"
            methods:
              - OPTIONS
              - POST
