export { getCompanies } from "./handlers/get-companies";
export { createCompany } from "./handlers/create-company";
export { createRestaurantType } from "./handlers/create-restaurant-type";
export { getRestaurants } from "./handlers/get-restaurants";
export { createRestaurant } from "./handlers/create-restaurant";
export { getRestaurant } from "./handlers/get-restaurant";
export { getRestaurantType } from "./handlers/get-restaurant-type";
export { getRestaurantsByCompanyId } from "./handlers/get-restaurants-by-companyId";
export { getCompanyById } from "./handlers/get-company-by-Id";
